export const VCAMERA_CONTRACT_VERSION = 3;
export const VCAMERA_PROJECT_VERSION = 4;

export const VCAMERA_LIMITS = {
  sceneTime: { minimum: 0, maximum: 3600 },
  positiveSceneTime: { minimum: 0.000001, maximum: 3600 },
  fps: { minimum: 1, maximum: 120 },
  actorHeight: { minimum: 0.1, maximum: 20 },
  seatHeight: { minimum: 0.1, maximum: 2.5 },
  poseIntensity: { minimum: 0, maximum: 1 },
  rotation: { minimum: -36000, maximum: 36000 },
  scale: { minimum: 0.05, maximum: 10000 },
  fov: { minimum: 1, maximum: 179 },
  focusDistance: { minimum: 0.05, maximum: 1_000_000 },
  followSpeed: { minimum: 1, maximum: 10 },
  stepCount: { minimum: 2, maximum: 20 },
  collections: {
    actors: 200,
    props: 500,
    cameras: 100,
    shots: 2000,
    cameraCuts: 2000,
    pathPointsPerEntity: 2000,
    actionMarkersPerActor: 2000,
    poseKeyframesPerActor: 2000,
    visibilityKeyframesPerProp: 2000,
    pathPointsPerPatch: 20000,
    metadataFields: 50,
  },
} as const;

export const VCAMERA_ENUMS = {
  safeFrameRatio: ["off", "9:16", "16:9", "1:1"],
  sceneEasing: ["smooth", "linear", "ease_in", "ease_out", "ease_in_out"],
  actorJointId: [
    "pelvis", "spine_lower", "spine_upper", "neck", "head",
    "upper_arm_l", "lower_arm_l", "hand_l", "upper_arm_r", "lower_arm_r", "hand_r",
    "upper_leg_l", "lower_leg_l", "foot_l", "upper_leg_r", "lower_leg_r", "foot_r",
  ],
  actorPosePreset: [
    "stand_neutral", "stand_attention", "sit_neutral", "sit_hands_on_thighs", "bow",
    "hand_on_chest", "raise_hand", "support_chin", "kneel", "crouch", "lie_supine", "lie_prone",
  ],
  propPreset: ["box", "thin_wall", "column", "platform", "obstacle", "door_frame", "stairs", "slope"],
  sourceType: ["primitive", "asset"],
  cameraMovementMode: ["static", "path", "follow"],
  cameraAimMode: ["manual", "actor", "point"],
  cameraTrackingPoint: ["head", "chest", "center"],
  cameraMotionPreset: [
    "push_in",
    "pull_out",
    "truck_left",
    "truck_right",
    "fixed_tracking",
    "lead_follow",
    "chase_follow",
    "orbit_left",
    "orbit_right",
    "crane_up",
    "crane_down",
    "pan_left",
    "pan_right",
    "tilt_up",
    "tilt_down",
    "zoom_in",
    "zoom_out",
    "dolly_zoom_in",
    "dolly_zoom_out",
  ],
  cameraCutAnchorKind: ["actor_path_point"],
} as const;

export const VCAMERA_DEFAULTS = {
  project: {
    version: VCAMERA_PROJECT_VERSION,
    name: "Virtual Shoot stage",
    fps: 24,
    duration: 1,
    safeFrameRatio: "off",
    activeCameraId: null,
  },
  actor: {
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    height: 1.75,
    pose: {
      rootOffset: [0, 0, 0],
      jointRotations: {},
      sourcePreset: "stand_neutral",
      presetParameters: { intensity: 1, mirror: false },
    },
  },
  primitiveProp: {
    position: [0, 0.5, 0],
    rotation: [0, 0, 0],
    visible: true,
    locked: false,
    sourceType: "primitive",
  },
  assetProp: {
    position: [0, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    visible: true,
    locked: false,
    sourceType: "asset",
  },
  stairsStepCount: 5,
  propPresets: {
    box: { name: "Cube", scale: [1, 1, 1] },
    thin_wall: { name: "Thin wall", scale: [2.8, 1.7, 0.12] },
    column: { name: "Column", scale: [0.35, 2.2, 0.35] },
    platform: { name: "Platform", scale: [2.2, 0.18, 1.5] },
    obstacle: { name: "Obstacle", scale: [1.1, 0.75, 0.7] },
    door_frame: { name: "Door frame", scale: [1.8, 2.25, 0.16] },
    stairs: { name: "Stairs", scale: [1.6, 0.75, 1.4] },
    slope: { name: "Slope", scale: [1.7, 0.65, 1.35] },
  },
  camera: {
    position: [0, 1.6, 4],
    rotation: [0, 0, 0],
    fov: 35,
    focusDistance: 4,
    duration: 3,
    movementMode: "static",
    aimMode: "manual",
    trackingActorId: null,
    trackingPoint: "chest",
    followOffset: [0, 1.6, 3],
    followSpeed: 6,
    motionPreset: null,
  },
} as const;

type FieldContract = {
  type: string;
  writable: boolean;
  required?: boolean;
  nullable?: boolean;
  clearable?: boolean;
  derived?: boolean;
  protected?: boolean;
  runtimeOnly?: boolean;
  minimum?: number;
  maximum?: number;
  enum?: keyof typeof VCAMERA_ENUMS;
  default?: unknown;
  reference?: string;
  itemType?: string;
  commands?: string[];
  notes?: string[];
};

const raw = (type: string, commands: string[], options: Omit<FieldContract, "type" | "writable" | "commands"> = {}): FieldContract => ({
  type,
  writable: true,
  commands,
  ...options,
});

const system = (type: string, options: Omit<FieldContract, "type" | "writable"> = {}): FieldContract => ({
  type,
  writable: false,
  ...options,
});

const time = (commands: string[], options: Omit<FieldContract, "type" | "writable" | "commands" | "minimum" | "maximum"> = {}): FieldContract => raw(
  "number",
  commands,
  { minimum: VCAMERA_LIMITS.sceneTime.minimum, maximum: VCAMERA_LIMITS.sceneTime.maximum, ...options },
);

const vec3 = (commands: string[], options: Omit<FieldContract, "type" | "writable" | "commands"> = {}): FieldContract => raw(
  "vec3",
  commands,
  options,
);

export const VCAMERA_FIELDS = {
  project: {
    version: system("integer", { derived: true, default: VCAMERA_PROJECT_VERSION, notes: ["Managed by normalization and compatibility upgrades."] }),
    name: raw("string", ["project set --name"], { required: true, default: VCAMERA_DEFAULTS.project.name }),
    fps: raw("number", ["project set --fps"], { required: true, ...VCAMERA_LIMITS.fps, default: VCAMERA_DEFAULTS.project.fps }),
    duration: system("number", { derived: true, minimum: 1, maximum: VCAMERA_LIMITS.sceneTime.maximum, default: VCAMERA_DEFAULTS.project.duration, notes: ["Derived from the latest authored global scene time."] }),
    safeFrameRatio: raw("enum", ["project set --safe-frame"], { required: true, enum: "safeFrameRatio", default: VCAMERA_DEFAULTS.project.safeFrameRatio }),
    cubes: raw("collection", ["prop add", "prop set", "prop translate", "prop delete", "prop path", "prop visibility"], { required: true, itemType: "prop" }),
    actors: raw("collection", ["actor add", "actor set", "actor translate", "actor delete", "actor path", "actor action", "actor pose"], { required: true, itemType: "actor" }),
    cameras: raw("collection", ["camera add", "camera set", "camera translate", "camera delete", "camera path"], { required: true, itemType: "camera" }),
    cameraCuts: raw("collection", ["cut add", "cut set", "cut delete", "cut clear", "shot add", "shot set", "shot delete"], { required: true, itemType: "cameraCut" }),
    shots: raw("collection", ["shot add", "shot set", "shot delete"], { required: true, itemType: "shot" }),
    activeCameraId: raw("id", ["project set --active-camera", "project set --clear-active-camera"], { nullable: true, clearable: true, reference: "camera", default: null }),
    currentTime: system("number", { runtimeOnly: true, ...VCAMERA_LIMITS.sceneTime }),
    isPlaying: system("boolean", { runtimeOnly: true }),
  },
  actor: {
    id: raw("id", ["actor add --id"], { required: true, notes: ["Stable after creation."] }),
    name: raw("string", ["actor add --name", "actor set --name"], { required: true, notes: ["Names may repeat; selectors must reject ambiguity."] }),
    position: vec3(["actor add --position", "actor set --position", "actor translate --delta"], { required: true, default: VCAMERA_DEFAULTS.actor.position }),
    rotation: vec3(["actor add --rotation", "actor set --rotation"], { required: true, ...VCAMERA_LIMITS.rotation, default: VCAMERA_DEFAULTS.actor.rotation }),
    height: raw("number", ["actor add --height", "actor set --height"], { required: true, ...VCAMERA_LIMITS.actorHeight, default: VCAMERA_DEFAULTS.actor.height }),
    lookAtActorId: raw("id", ["actor set --look-at-actor", "actor set --clear-look-at-actor", "actor set --clear-look-at"], { nullable: true, clearable: true, reference: "actor" }),
    lookAtPoint: vec3(["actor set --look-at-point", "actor set --clear-look-at-point", "actor set --clear-look-at"], { nullable: true, clearable: true }),
    actionMarkers: raw("collection", ["actor action add", "actor action set", "actor action delete", "actor action clear"], { itemType: "actionMarker" }),
    pose: raw("object", ["actor add --pose-preset|--pose-json|--pose-file", "actor set --pose-preset|--pose-json|--pose-file|--reset-pose"], { required: true, itemType: "actorPose" }),
    poseKeyframes: raw("collection", ["actor pose add", "actor pose set", "actor pose update", "actor pose delete", "actor pose clear"], { required: true, itemType: "actorPoseKeyframe" }),
    pathPoints: raw("collection", ["actor path add", "actor path set", "actor path update", "actor path delete", "actor path clear"], { required: true, itemType: "actorPathPoint" }),
  },
  actorPose: {
    rootOffset: vec3(["actor pose", "actor add|set --pose-json|--pose-file"], { required: true, notes: ["Actor-local meters. Does not change actor.position."] }),
    jointRotations: raw("joint_rotation_map", ["actor pose", "actor add|set --pose-json|--pose-file"], { required: true, enum: "actorJointId", notes: ["Actor-local XYZ degrees."] }),
    sourcePreset: raw("enum", ["actor pose --preset", "actor add|set --pose-preset"], { nullable: true, enum: "actorPosePreset", notes: ["Metadata only; presets are resolved into rootOffset and jointRotations before writing."] }),
    presetParameters: raw("object", ["actor pose --seat-height|--intensity|--mirror"], { notes: ["Optional seatHeight, intensity, and mirror provenance."] }),
  },
  actorPoseKeyframe: {
    id: raw("id", ["actor pose add --id", "actor pose set --points-json"], { required: true, notes: ["Stable when updating a pose keyframe."] }),
    time: time(["actor pose add --time", "actor pose update --time", "actor pose set --points-json"], { required: true, notes: ["Absolute global scene time."] }),
    pose: raw("object", ["actor pose add|update", "actor pose set --points-json"], { required: true, itemType: "actorPose" }),
    easing: raw("enum", ["actor pose add|update --easing", "actor pose update --clear-easing"], { nullable: true, clearable: true, enum: "sceneEasing" }),
  },
  actorPathPoint: {
    id: raw("id", ["actor path add --id", "actor path set --points-json"], { required: true, notes: ["Stable when updating a path point."] }),
    time: time(["path add --time", "path update --time", "path set --points-json"], { required: true }),
    position: vec3(["path add --position", "path update --position", "path set --points-json"], { required: true }),
    yaw: raw("number", ["path add --yaw", "path update --yaw", "path update --clear-yaw", "path set --points-json"], { nullable: true, clearable: true, ...VCAMERA_LIMITS.rotation }),
    easing: raw("enum", ["path add --easing", "path update --easing", "path update --clear-easing", "path set --points-json"], { nullable: true, clearable: true, enum: "sceneEasing" }),
  },
  propPathPoint: {
    id: raw("id", ["prop path add --id", "prop path set --points-json"], { required: true, notes: ["Stable when updating a path point."] }),
    time: time(["prop path add --time", "prop path update --time", "prop path set --points-json"], { required: true }),
    position: vec3(["prop path add --position", "prop path update --position", "prop path set --points-json"], { required: true }),
    rotation: vec3(["prop path add --rotation", "prop path update --rotation", "prop path update --clear-rotation", "prop path set --points-json"], { nullable: true, clearable: true, ...VCAMERA_LIMITS.rotation }),
    easing: raw("enum", ["prop path add --easing", "prop path update --easing", "prop path update --clear-easing", "prop path set --points-json"], { nullable: true, clearable: true, enum: "sceneEasing" }),
  },
  cameraPathPoint: {
    id: raw("id", ["camera path add --id", "camera path set --points-json", "camera preset"], { required: true, notes: ["Stable when updating a path point."] }),
    time: time(["camera path add --time", "camera path update --time", "camera path set --points-json", "camera preset --start-time"], { required: true }),
    position: vec3(["camera path add --position", "camera path update --position", "camera path set --points-json", "camera preset"], { required: true }),
    easing: raw("enum", ["camera path add --easing", "camera path update --easing", "camera path update --clear-easing", "camera path set --points-json", "camera preset --easing"], { nullable: true, clearable: true, enum: "sceneEasing" }),
    rotation: vec3(["camera path add --rotation", "camera path update --rotation", "camera path update --clear-rotation", "camera path set --points-json"], { nullable: true, clearable: true, ...VCAMERA_LIMITS.rotation }),
    fov: raw("number", ["camera path add --fov", "camera path update --fov", "camera path update --clear-fov", "camera path set --points-json"], { nullable: true, clearable: true, ...VCAMERA_LIMITS.fov }),
    focusDistance: raw("number", ["camera path add --focus-distance", "camera path update --focus-distance", "camera path update --clear-focus-distance", "camera path set --points-json"], { nullable: true, clearable: true, ...VCAMERA_LIMITS.focusDistance }),
  },
  actionMarker: {
    id: raw("id", ["actor action add --id"], { required: true, notes: ["Stable when using actor action set."] }),
    time: time(["actor action add --time", "actor action set --time"], { required: true }),
    action: raw("string", ["actor action add --action", "actor action set --action"], { required: true }),
    targetActorId: raw("id", ["actor action add --target-actor", "actor action set --target-actor", "actor action set --clear-target-actor", "actor action set --clear-targets"], { nullable: true, clearable: true, reference: "actor" }),
    targetPoint: vec3(["actor action add --target-point", "actor action set --target-point", "actor action set --clear-target-point", "actor action set --clear-targets"], { nullable: true, clearable: true }),
  },
  prop: {
    id: raw("id", ["prop add --id"], { required: true, notes: ["Stable after creation."] }),
    name: raw("string", ["prop add --name", "prop set --name"], { required: true }),
    position: vec3(["prop add --position", "prop set --position", "prop translate --delta"], { required: true }),
    rotation: vec3(["prop add --rotation", "prop set --rotation"], { required: true, ...VCAMERA_LIMITS.rotation }),
    scale: vec3(["prop add --scale", "prop set --scale"], { required: true, ...VCAMERA_LIMITS.scale }),
    visible: raw("boolean", ["prop set --visible"], { required: true, default: true }),
    locked: raw("boolean", ["prop set --locked"], { required: true, default: false }),
    propPreset: raw("enum", ["prop add --preset", "prop set --preset", "prop set --clear-preset"], { nullable: true, clearable: true, enum: "propPreset" }),
    stepCount: raw("integer", ["prop add --steps", "prop set --steps", "prop set --clear-steps"], { nullable: true, clearable: true, ...VCAMERA_LIMITS.stepCount, default: VCAMERA_DEFAULTS.stairsStepCount }),
    sourceType: raw("enum", ["prop add --source-type", "prop set --source-type"], { required: true, enum: "sourceType", default: "primitive" }),
    assetId: raw("id", ["prop add --asset-id", "prop set --asset-id", "prop set --clear-asset"], { nullable: true, clearable: true, reference: "ownedModelAsset" }),
    visibilityKeyframes: raw("collection", ["prop visibility add", "prop visibility set", "prop visibility delete", "prop visibility clear"], { itemType: "visibilityKeyframe" }),
    pathPoints: raw("collection", ["prop path add", "prop path set", "prop path update", "prop path delete", "prop path clear"], { required: true, itemType: "propPathPoint" }),
  },
  visibilityKeyframe: {
    id: raw("id", ["prop visibility add --id"], { required: true, notes: ["Stable when using prop visibility set."] }),
    time: time(["prop visibility add --time", "prop visibility set --time"], { required: true }),
    visible: raw("boolean", ["prop visibility add --visible", "prop visibility set --visible"], { required: true }),
  },
  camera: {
    id: raw("id", ["camera add --id"], { required: true, notes: ["Stable after creation."] }),
    name: raw("string", ["camera add --name", "camera set --name"], { required: true }),
    position: vec3(["camera add --position", "camera set --position", "camera translate --delta"], { required: true, default: VCAMERA_DEFAULTS.camera.position }),
    rotation: vec3(["camera add --rotation", "camera set --rotation"], { required: true, ...VCAMERA_LIMITS.rotation, default: VCAMERA_DEFAULTS.camera.rotation }),
    fov: raw("number", ["camera add --fov", "camera set --fov"], { required: true, ...VCAMERA_LIMITS.fov, default: VCAMERA_DEFAULTS.camera.fov }),
    focusDistance: raw("number", ["camera add --focus-distance", "camera set --focus-distance"], { required: true, ...VCAMERA_LIMITS.focusDistance, default: VCAMERA_DEFAULTS.camera.focusDistance }),
    duration: raw("number", ["camera add --duration", "camera set --duration"], { required: true, ...VCAMERA_LIMITS.positiveSceneTime, default: VCAMERA_DEFAULTS.camera.duration, notes: ["Camera metadata; project duration is derived independently."] }),
    movementMode: raw("enum", ["camera set --movement-mode"], { required: true, enum: "cameraMovementMode", default: VCAMERA_DEFAULTS.camera.movementMode }),
    aimMode: raw("enum", ["camera set --aim-mode"], { required: true, enum: "cameraAimMode", default: VCAMERA_DEFAULTS.camera.aimMode }),
    trackingActorId: raw("id", ["camera set --tracking-actor", "camera set --clear-tracking"], { nullable: true, clearable: true, reference: "actor", default: null }),
    lookAtPoint: vec3(["camera set --look-at-point", "camera set --clear-look-at"], { nullable: true, clearable: true }),
    trackingPoint: raw("enum", ["camera set --tracking-point"], { required: true, enum: "cameraTrackingPoint", default: VCAMERA_DEFAULTS.camera.trackingPoint }),
    followOffset: vec3(["camera set --follow-offset"], { required: true, default: VCAMERA_DEFAULTS.camera.followOffset }),
    followSpeed: raw("number", ["camera set --follow-speed"], { required: true, ...VCAMERA_LIMITS.followSpeed, default: VCAMERA_DEFAULTS.camera.followSpeed }),
    motionPreset: raw("enum", ["camera set --motion-preset", "camera set --clear-motion-preset", "camera preset"], { nullable: true, clearable: true, enum: "cameraMotionPreset", default: null, notes: ["Metadata only. Applying a preset generates editable global-time keyframes or follow settings."] }),
    pathPoints: raw("collection", ["camera path add", "camera path set", "camera path update", "camera path delete", "camera path clear"], { required: true, itemType: "cameraPathPoint" }),
  },
  shot: {
    id: raw("id", ["shot add --id"], { required: true, notes: ["Stable after creation."] }),
    name: raw("string", ["shot add --name", "shot set --name"], { required: true }),
    startTime: time(["shot add --start-time", "shot set --start-time"], { required: true }),
    endTime: time(["shot add --end-time", "shot add --duration", "shot set --end-time", "shot set --duration"], { required: true }),
    cameraId: raw("id", ["shot add --camera", "shot set --camera"], { required: true, reference: "camera" }),
    locked: raw("boolean", ["shot add --locked", "shot set --locked"], { required: true, default: false }),
    metadata: raw("scalarMap", ["shot add --metadata-json", "shot set --metadata-json"], { required: true, default: {} }),
  },
  cameraCut: {
    id: raw("id", ["cut add --id"], { required: true, notes: ["Stable after creation."] }),
    time: time(["cut add --time", "cut set --time", "cut add --actor --point", "cut set --actor --point"], { required: true }),
    cameraId: raw("id", ["cut add --camera", "cut set --camera"], { required: true, reference: "camera" }),
    shotId: system("id", { nullable: true, reference: "shot", notes: ["Managed by shot commands."] }),
    anchor: raw("object", ["cut add --actor --point", "cut set --actor --point", "cut set --clear-anchor"], { nullable: true, clearable: true, itemType: "cameraCutAnchor" }),
  },
  cameraCutAnchor: {
    kind: system("enum", { enum: "cameraCutAnchorKind", default: "actor_path_point" }),
    actorId: raw("id", ["cut add --actor", "cut set --actor"], { required: true, reference: "actor" }),
    pointId: raw("id", ["cut add --point", "cut set --point"], { required: true, reference: "actor.pathPoint" }),
  },
} as const;

export const VCAMERA_CONTRACT = {
  contractVersion: VCAMERA_CONTRACT_VERSION,
  projectVersion: VCAMERA_PROJECT_VERSION,
  timeline: {
    mode: "single_global_timeline",
    unit: "seconds",
    minimum: VCAMERA_LIMITS.sceneTime.minimum,
    maximum: VCAMERA_LIMITS.sceneTime.maximum,
    description: "Every path point, pose keyframe, action marker, visibility keyframe, shot boundary, and camera cut uses absolute time from scene second 0.",
    duplicatePathTime: {
      version3: "reject",
      version4: "reject",
      legacyMigration: "stable_offset_1ms",
    },
    interpolation: {
      positionPath: "piecewise_eased_linear",
      easingAppliesTo: "time_progress_only",
      identicalEndpointBehavior: "exact_hold",
      overshootAllowed: false,
      afterLastKeyframe: "exact_final_hold",
      rotationPath: "shortest_angle",
      poseRotationPath: "quaternion_slerp",
    },
  },
  spatial: {
    unit: "meter",
    handedness: "right",
    axes: {
      x: "+X right at zero camera yaw",
      y: "+Y up",
      z: "-Z forward at zero camera yaw",
    },
    groundPlane: "XZ at Y=0",
    rotation: {
      unit: "degrees",
      components: ["pitch", "yaw", "roll"],
      actorOrder: "XYZ",
      propOrder: "XYZ",
      cameraOrder: "YXZ",
      positiveYawDirection: "from -Z toward -X",
    },
    actor: { positionAnchor: "feet", modelForwardAxis: "+Z" },
    prop: {
      positionAnchor: "geometry_center",
      defaultGrounding: "position.y equals half world height",
      assetPolicy: "named_proxy_geometry",
      boundingBox: "available_from_proxy_geometry",
    },
    camera: {
      forwardAxis: "-Z",
      upAxis: "+Y",
      fovType: "vertical",
      fovUnit: "degrees",
      followOffsetSpace: "tracked_actor_local",
    },
  },
  safeFrame: {
    mode: "output_crop",
    ratios: VCAMERA_ENUMS.safeFrameRatio,
  },
  proxyGeometry: {
    realAssetRendering: false,
    assetIdEffect: "semantic-reference-only",
    positionAnchor: "geometry_center",
    dimensionUnit: "meter",
    missingPresetFallback: "box",
    unknownPresetPolicy: "reject",
    presets: VCAMERA_DEFAULTS.propPresets,
    worldBoundingBox: "derived_from_proxy_geometry_position_rotation_scale",
  },
  runtimeEffects: {
    "actor.pathPoints.position": "behavioral",
    "actor.pathPoints.yaw": "behavioral",
    "actor.pathPoints.easing": "behavioral",
    "actor.pose": "rendered/behavioral",
    "actor.poseKeyframes": "rendered/behavioral",
    "actor.pose.sourcePreset": "metadata-only",
    "actor.actionMarkers": "semantic/metadata-only",
    "prop.pathPoints.position": "behavioral",
    "prop.pathPoints.rotation": "behavioral",
    "prop.pathPoints.easing": "behavioral",
    "camera.pathPoints.position": "behavioral",
    "camera.pathPoints.rotation": "behavioral",
    "camera.pathPoints.fov": "rendered",
    "camera.pathPoints.focusDistance": "metadata-only",
    "camera.pathPoints.easing": "behavioral",
    "camera.duration": "metadata-only",
    "camera.motionPreset": "metadata-only",
  },
  entities: {
    actor: { projectField: "actors", idField: "id", nameField: "name", maximum: VCAMERA_LIMITS.collections.actors },
    prop: { projectField: "cubes", idField: "id", nameField: "name", maximum: VCAMERA_LIMITS.collections.props },
    camera: { projectField: "cameras", idField: "id", nameField: "name", maximum: VCAMERA_LIMITS.collections.cameras },
    shot: { projectField: "shots", idField: "id", nameField: "name", maximum: VCAMERA_LIMITS.collections.shots },
    cameraCut: { projectField: "cameraCuts", idField: "id", maximum: VCAMERA_LIMITS.collections.cameraCuts },
  },
  fields: VCAMERA_FIELDS,
  enums: VCAMERA_ENUMS,
  defaults: VCAMERA_DEFAULTS,
  limits: VCAMERA_LIMITS,
  rules: [
    { id: "global_timeline", description: "All authored times are absolute global scene seconds in the range 0..3600." },
    { id: "stable_ids", description: "Internal references use stable IDs. Renaming an entity never changes its ID." },
    { id: "duplicate_names", description: "Names may repeat. Name selectors that match more than one entity fail and require an ID." },
    { id: "active_camera_reference", description: "activeCameraId is null or references an existing camera." },
    { id: "actor_look_at_reference", description: "Actor lookAtActorId references another existing actor, never itself." },
    { id: "camera_follow_reference", description: "movementMode=follow requires trackingActorId." },
    { id: "camera_actor_aim_reference", description: "aimMode=actor requires trackingActorId." },
    { id: "camera_point_aim_reference", description: "aimMode=point requires lookAtPoint." },
    { id: "owned_asset", description: "sourceType=asset requires an assetId owned by the current user; arbitrary external model URLs are unsupported." },
    { id: "shot_order", description: "Shots are sorted by startTime, end after they start, and do not overlap on the main timeline." },
    { id: "shot_cut_sync", description: "Each shot owns one camera cut at shot.startTime with the same cameraId." },
    { id: "cut_anchor_sync", description: "An actor-path-point camera cut anchor uses the same absolute time as its referenced path point." },
    { id: "zero_time_origin", description: "A zero-time path point is the canonical initial position. Raw set --position refuses to diverge from it unless --sync-origin is explicit." },
    { id: "derived_duration", description: "Project duration is derived from the latest authored path, pose keyframe, marker, shot end, or camera cut." },
    { id: "duplicate_path_time", description: "Version 3 and 4 reject duplicate path times within the same entity. Version 1 and 2 inspection migrates duplicates deterministically by stable ID in 1ms steps." },
    { id: "pose_independence", description: "actor.pose changes internal body posture only and never moves actor.position or actor.pathPoints." },
    { id: "pose_tracking", description: "Camera head, chest, and center tracking points follow the actor's current rendered pose." },
    { id: "actor_delete_cleanup", description: "Deleting an actor clears actor look-at/action references, removes its anchored cuts, and resets cameras that tracked it using the same cleanup rules as the Virtual Shoot editor." },
    { id: "camera_lifecycle_cleanup", description: "Adding the first camera makes it active. Deleting a camera removes its shots and cuts; deleting the active camera selects the first remaining camera or null." },
    { id: "shot_lifecycle_cleanup", description: "Adding or editing a shot creates or synchronizes its managed camera cut. Deleting a shot also deletes that managed cut." },
    { id: "revision_safety", description: "Every mutation sends baseRevision and fails on conflicts without overwrite retries." },
    { id: "atomic_scene_apply", description: "scene apply strictly validates a canonical complete project locally, rejects implicit normalization, and writes all scene fields to one explicit node in one revision-protected request." },
    { id: "create_only_scene_apply", description: "scene apply --expected-empty maps to mode=create_only so a populated target cannot be replaced after inspection." },
  ],
  rawCommands: [
    "scene apply",
    "project set",
    "actor add|set|translate|delete|path|action|pose",
    "prop add|set|translate|delete|path|visibility",
    "camera add|set|translate|delete|path|preset",
    "shot add|set|delete",
    "cut add|set|delete|clear",
  ],
  rawCommandEffects: {
    "actor|prop|camera set --sync-origin": ["Updates the entity base position and every zero-time path point only."],
    "actor|prop|camera translate": ["Translates the entity base position and every path point position by the declared delta."],
    "actor delete": ["Cleans actor references, actor-anchored cuts, and camera tracking state according to actor_delete_cleanup."],
    "camera add": ["Sets activeCameraId only when no active camera exists."],
    "camera delete": ["Removes dependent shots and cuts and updates activeCameraId according to camera_lifecycle_cleanup."],
    "shot add|set": ["Creates or synchronizes the shot-managed camera cut."],
    "shot delete": ["Removes the shot-managed camera cut."],
    "cut add|set --actor --point": ["Copies the referenced actor path point's global time into the cut."],
    "camera preset": ["Generates editable global-time camera keyframes or explicit follow settings and records motionPreset as provenance metadata."],
  },
  compoundHelpers: {
    "camera follow": {
      stableForAutomation: false,
      status: "compound_helper",
      modifies: ["camera.movementMode", "camera.aimMode", "camera.trackingActorId", "camera.trackingPoint", "camera.followOffset", "camera.followSpeed"],
      optionalModifies: ["camera.motionPreset"],
      warning: "Automation should use camera set with explicit raw fields.",
    },
    "camera aim": {
      stableForAutomation: false,
      status: "compound_helper",
      modifiesByMode: {
        actor: ["camera.aimMode", "camera.trackingActorId"],
        point: ["camera.aimMode", "camera.lookAtPoint"],
        manual: ["camera.aimMode"],
      },
      warning: "Automation should use camera set with explicit raw fields.",
    },
    "camera preset": {
      stableForAutomation: true,
      status: "node_preset_generator",
      required: ["--camera", "--preset", "--duration"],
      optional: ["--actor", "--start-time", "--easing", "--amount", "--preserve-subject-scale"],
      result: "Editable global-time camera keyframes or follow settings.",
      customAlternative: "Use camera set and camera path add|set|update for unrestricted valid parameters.",
    },
  },
  derivedFields: ["project.version", "project.duration", "cameraCut.shotId", "cameraCut.time when anchor is set"],
  runtimeOnlyFields: ["project.currentTime", "project.isPlaying"],
  protectedFields: [
    "project.takes",
    "project.savedScenes",
    "project.activeSavedSceneId",
    "recording.*",
    "media.*",
    "task.*",
    "result.*",
    "billing.*",
  ],
  mutationSafety: {
    endpoint: "/canvas/{canvasId}/v-camera",
    confirmationFlag: "--yes",
    dryRunFlag: "--dry-run",
    revisionField: "baseRevision",
    retriesOnConflict: false,
    genericNodeDataUpdateAllowed: false,
    atomicSceneApply: {
      command: "scene apply",
      required: ["--canvas-id", "--node-id", "--file"],
      optional: ["--expected-empty", "--dry-run", "--yes", "--json"],
      projectVersion: VCAMERA_PROJECT_VERSION,
      singleRequest: true,
      expectedEmptyMode: "create_only",
      protectedFieldsPreserved: true,
      validation: {
        localBeforeNetwork: true,
        canonicalCompleteProject: true,
        implicitNormalization: "reject",
        shotMetadata: "maximum 50 fields; keys 1..80 characters; values JSON scalars",
      },
    },
  },
} as const;

export function getVCameraCapabilities(): typeof VCAMERA_CONTRACT {
  return JSON.parse(JSON.stringify(VCAMERA_CONTRACT)) as typeof VCAMERA_CONTRACT;
}
